grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin123
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  grafana.ini:
    server:
      root_url: %(protocol)s://%(domain)s/grafana/
      serve_from_sub_path: true
  ingress:
    enabled: false

prometheus:
  enabled: true
  service:
    type: ClusterIP
  prometheusSpec:
    routePrefix: /prometheus
    retention: 24h
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi

alertmanager:
  enabled: true
  service:
    type: ClusterIP
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi


