apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
    activeColor: {{ .Values.backend.activeColor | default "blue" }}
  ports:
    - port: {{ .Values.backend.port | default 3000 }}
      targetPort: {{ .Values.backend.port | default 3000 }}
  type: ClusterIP


