{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend
      activeColor: {{ .Values.backend.activeColor | default "blue" }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
{{- end }}
