apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  labels:
    app: frontend
    activeColor: blue
spec:
  replicas: {{ .Values.frontend.replicas | default 1 }}
  selector:
    matchLabels:
      app: frontend
      activeColor: blue
  template:
    metadata:
      labels:
        app: frontend
        activeColor: blue
    spec:
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ .Values.frontend.blueImage | default .Values.frontend.image | quote }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.port | default 80 }}


