mongo:
  # Jenkins sets this via --set-string mongo.uri=...
  uri: ""

# Jenkins sets this via --set host=$PROD_HOST
host: ""

backend:
  image: "docker.io/toeho/rmit-store-backend:latest"
  blueImage:  "docker.io/toeho/rmit-store-backend:latest"
  greenImage: "docker.io/toeho/rmit-store-backend:latest"
  env:
    JWT_SECRET: "prodsecret"
  replicas: 1
  activeColor: "blue"
  port: 3000

frontend:
  image: "docker.io/toeho/rmit-store-frontend:latest"
  blueImage:  "docker.io/toeho/rmit-store-frontend:latest"
  greenImage: "docker.io/toeho/rmit-store-frontend:latest"
  replicas: 1
  activeColor: "blue"
  port: 80

monitoring:
  enabled: false


